import turtle
turtle.showturtle()
turtle.write("Jack")
turtle.forward(300)
turtle.color("red")
turtle.left(90)
turtle.forward(300)
turtle.goto(0,50)
turtle.goto(0,0)
turtle.penup()
turtle.goto(0,300)
turtle.goto(0,0)
turtle.pendown()
turtle.goto(50,50)
turtle.circle(100)

